on:
  pull_request:
    paths:
      - '**.java'

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run checkstyle
        uses: ViMatviienko/checkstyle-github-action@main
        with:
          review_secret: ${{ secrets.PAT }}
          level: 'warning'
          reporter: 'github-pr-review'
          checkstyle_config: ${{ github.workspace }}/checkstyle/cloud.xml
